# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3f26bf2ef17007bca45186462209d62c2b3946beb05c23927af68d85beb1a602103ad23016a5e7f9a7dd5bc1cc461d4f5ee16a20ae054cbc3b63b66d7f90b9

test:
  secret_key_base: 089f80adf0de352faf1dbf5a29a3f04cb942c4bb554ec69f55b5e3cc1dfa7307dfe129eee2128d430358b43bd720a8410086d375104e1669e8b5f5239def9fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
